# Generated by Django 4.1.6 on 2023-03-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhospital2",
            name="physicians_onboarded",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="hospital2",
            name="physicians_onboarded",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
