# Generated by Django 4.1.6 on 2023-03-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0003_historicalhospital2_soft_delete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhospital2",
            name="sd",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalhospital2",
            name="sd2",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="hospital2",
            name="sd",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hospital2",
            name="sd2",
            field=models.BooleanField(null=True),
        ),
    ]
