# Generated by Django 4.1.6 on 2023-03-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0004_historicalhospital2_sd_historicalhospital2_sd2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhospital2",
            name="email",
            field=models.EmailField(default="", max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="hospital2",
            name="email",
            field=models.EmailField(default="", max_length=60, null=True),
        ),
    ]
