# Generated by Django 4.1.7 on 2023-03-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0007_alter_hospital2_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hospital2",
            options={"ordering": ["-is_manual", "-created_at"]},
        ),
    ]
