# Generated by Django 4.1.7 on 2023-03-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0008_alter_hospital2_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalhospital2",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="hospital2",
            old_name="modified_at",
            new_name="updated_at",
        ),
    ]
