# Generated by Django 4.1.7 on 2023-03-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0010_historicalhospital2_is_manual_time_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalHospital2",
        ),
    ]
