# Generated by Django 4.1.7 on 2023-03-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0012_alter_hospital2_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital2",
            name="phone",
            field=models.CharField(default="", max_length=12, null=True),
        ),
    ]
