# Generated by Django 4.1.7 on 2023-03-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0014_hospital2_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital2",
            name="last_name",
            field=models.CharField(default="", max_length=40, null=True),
        ),
    ]
