# Generated by Django 4.1.6 on 2023-03-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quickstarthospital1",
            name="hospital_address",
        ),
    ]
