# Generated by Django 4.1.6 on 2023-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0004_alter_quickstarthospital1_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quickstarthospital1",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="quickstarthospital1",
            name="hospital_zip",
            field=models.CharField(default="", max_length=40, null=True),
        ),
    ]
