# Generated by Django 4.1.6 on 2023-03-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0006_quickstarthospital1_has_physicians"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquickstartphysician",
            name="hospital_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New Hospital"),
                    ("invite", "Recently Invited"),
                    ("onboarded", "Fully Onboarded"),
                    ("na", "Don't Assign"),
                ],
                default="",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="quickstartphysician",
            name="hospital_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New Hospital"),
                    ("invite", "Recently Invited"),
                    ("onboarded", "Fully Onboarded"),
                    ("na", "Don't Assign"),
                ],
                default="",
                max_length=25,
            ),
        ),
    ]
