# Generated by Django 4.1.6 on 2023-03-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0004_historicalhospital2_sd_historicalhospital2_sd2_and_more"),
        (
            "quickstart",
            "0007_alter_historicalquickstartphysician_hospital_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="quickstartphysician",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qsp",
                to="medical.hospital2",
            ),
        ),
    ]
