# Generated by Django 4.1.7 on 2023-03-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0008_alter_quickstartphysician_hospital"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalquickstartphysician",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quickstartphysician",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
    ]
