# Generated by Django 4.1.7 on 2023-03-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0010_historicalquickstartphysician_is_complete_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalquickStartPhysician",
        ),
    ]
