# Generated by Django 4.1.7 on 2023-03-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0011_delete_historicalquickstartphysician"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickstarthospital1",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
    ]
