# Generated by Django 4.1.6 on 2023-03-05 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pproducts.fields
import pproducts.helper_functions
import pproducts.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_recovery_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Shop-Recovery ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "short_description",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=pproducts.helper_functions.user_directory_path_products,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "UPC",
                    models.CharField(blank=True, default="", max_length=25, null=True),
                ),
                ("SKU", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty_sp",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            options={
                "ordering": ["specialty_sp"],
            },
        ),
        migrations.CreateModel(
            name="ProductTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_recovery_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Shop Recovery Id"
                    ),
                ),
                ("tag", models.CharField(default="", max_length=50, unique=True)),
                (
                    "shop_recovery_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=512, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        default="none",
                        null=True,
                        related_name="specialties",
                        to="pproducts.product",
                    ),
                ),
                (
                    "related_specialty",
                    models.ManyToManyField(
                        blank=True, null=True, to="pproducts.specialty"
                    ),
                ),
            ],
            options={
                "ordering": ["tag"],
            },
        ),
        migrations.CreateModel(
            name="Physician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_recovery_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shop_recovery_name",
                    models.CharField(blank=True, default=" ", max_length=40),
                ),
                ("firstName", models.CharField(blank=True, default=" ", max_length=40)),
                ("lastName", models.CharField(blank=True, default=" ", max_length=40)),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=pproducts.helper_functions.user_directory_path_physicians,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, default="", max_length=50)),
                ("services", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "productitems_previous",
                    pproducts.fields.MyJsonField(blank=True, null=True),
                ),
                ("about_me", models.TextField(blank=True, default="", max_length=512)),
                (
                    "products",
                    pproducts.fields.MyJsonField(
                        blank=True,
                        default=pproducts.models.physicianDefaultProducts,
                        null=True,
                    ),
                ),
                ("is_onboarded", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "facility",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical.hospital2",
                    ),
                ),
                (
                    "productitems",
                    models.ManyToManyField(
                        blank=True, null=True, to="pproducts.product"
                    ),
                ),
                (
                    "specialty_ph",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="physicians",
                        to="pproducts.producttags",
                    ),
                ),
            ],
            options={
                "ordering": ["firstName"],
            },
        ),
        migrations.CreateModel(
            name="LinkedProductTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(default="", max_length=50)),
                (
                    "description",
                    models.TextField(default="", max_length=1000, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "parentTag",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parenttags",
                        to="pproducts.producttags",
                    ),
                ),
                (
                    "physician",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedtags",
                        to="pproducts.physician",
                    ),
                ),
                ("products", models.ManyToManyField(null=True, to="pproducts.product")),
            ],
            options={
                "ordering": ["tag"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProductTags",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "shop_recovery_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Shop Recovery Id"
                    ),
                ),
                ("tag", models.CharField(db_index=True, default="", max_length=50)),
                (
                    "shop_recovery_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=512, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical product tags",
                "verbose_name_plural": "historical product tagss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "shop_recovery_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Shop-Recovery ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "short_description",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("picture", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "UPC",
                    models.CharField(blank=True, default="", max_length=25, null=True),
                ),
                ("SKU", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical product",
                "verbose_name_plural": "historical products",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPhysician",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "shop_recovery_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shop_recovery_name",
                    models.CharField(blank=True, default=" ", max_length=40),
                ),
                ("firstName", models.CharField(blank=True, default=" ", max_length=40)),
                ("lastName", models.CharField(blank=True, default=" ", max_length=40)),
                ("picture", models.TextField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, default="", max_length=50)),
                ("services", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "productitems_previous",
                    pproducts.fields.MyJsonField(blank=True, null=True),
                ),
                ("about_me", models.TextField(blank=True, default="", max_length=512)),
                (
                    "products",
                    pproducts.fields.MyJsonField(
                        blank=True,
                        default=pproducts.models.physicianDefaultProducts,
                        null=True,
                    ),
                ),
                ("is_onboarded", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="medical.hospital2",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical physician",
                "verbose_name_plural": "historical physicians",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
