# Generated by Django 4.1.6 on 2023-03-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pproducts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphysician",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="physician",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
    ]
