# Generated by Django 4.1.6 on 2023-03-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pproducts", "0002_historicalphysician_soft_delete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalproducttags",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producttags",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
    ]
