# Generated by Django 4.1.6 on 2023-03-13 04:32

from django.db import migrations, models
import django.db.models.deletion
import pproducts.models


class Migration(migrations.Migration):

    dependencies = [
        ("pproducts", "0004_historicalphysician_user_delete_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to=pproducts.models.user_directory_path_images_product,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pproducts.product",
                    ),
                ),
            ],
        ),
    ]
