# Generated by Django 4.1.6 on 2023-03-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pproducts", "0006_alter_productimages_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimages",
            name="image",
            field=models.CharField(default="", max_length=256, null=True),
        ),
    ]
