# Generated by Django 4.1.6 on 2023-03-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pproducts", "0007_alter_productimages_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphysician",
            name="sd",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="physician",
            name="sd",
            field=models.BooleanField(default=False),
        ),
    ]
