# Generated by Django 4.1.7 on 2023-03-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pproducts", "0008_historicalphysician_sd_physician_sd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="price",
            field=models.CharField(blank=True, default="", max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(blank=True, default="", max_length=8, null=True),
        ),
    ]
