# Generated by Django 4.1.7 on 2023-03-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pproducts", "0009_alter_historicalproduct_price_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="price",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
    ]
