# Generated by Django 4.1.7 on 2023-03-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pproducts", "0010_alter_historicalproduct_price_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="previous_specialty_string",
            field=models.CharField(default="", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="previous_specialty_string",
            field=models.CharField(default="", max_length=256, null=True),
        ),
    ]
