# Generated by Django 4.1.7 on 2023-03-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pproducts", "0011_historicalproduct_previous_specialty_string_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproduct",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalproducttags",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="HistoricalPhysician",
        ),
        migrations.DeleteModel(
            name="HistoricalProduct",
        ),
        migrations.DeleteModel(
            name="HistoricalProductTags",
        ),
    ]
