# Generated by Django 4.1.7 on 2023-03-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superuseractions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistorytable",
            name="entity_id",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="userhistorytable",
            name="entity_name",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="userhistorytable",
            name="entity_type",
            field=models.CharField(default="", max_length=64, null=True),
        ),
    ]
