# Generated by Django 4.1.7 on 2023-03-16 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("superuseractions", "0002_userhistorytable_entity_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhistorytable",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ahistory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
