# Generated by Django 4.1.7 on 2023-03-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superuseractions", "0008_userhistorytable_page_link3"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistorytable",
            name="age_link3",
            field=models.CharField(default="", max_length=64, null=True),
        ),
    ]
