# Generated by Django 4.1.7 on 2023-03-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("superuseractions", "0009_userhistorytable_age_link3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userhistorytable",
            name="age_link3",
        ),
        migrations.RemoveField(
            model_name="userhistorytable",
            name="page_link2",
        ),
        migrations.RemoveField(
            model_name="userhistorytable",
            name="page_link3",
        ),
    ]
