# Generated by Django 4.1.7 on 2023-03-20 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("superuseractions", "0011_alter_userhistorytable_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickInviteLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(default="", max_length=50)),
                ("send_time", models.DateTimeField(auto_now_add=True)),
                ("entity_name", models.CharField(default="", max_length=25)),
                ("entity_type", models.CharField(default="", max_length=30)),
                (
                    "message",
                    models.IntegerField(
                        choices=[(0, "Default"), (1, "Custom")], default=0
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
