# Generated by Django 4.1.7 on 2023-03-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("superuseractions", "0012_quickinvitelogs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quickinvitelogs",
            options={"ordering": ["-send_time"]},
        ),
    ]
