# Generated by Django 4.1.7 on 2023-03-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superuseractions", "0013_alter_quickinvitelogs_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickinvitelogs",
            name="action",
            field=models.CharField(default="", max_length=64),
        ),
    ]
