# Generated by Django 4.1.7 on 2023-03-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superuseractions", "0014_quickinvitelogs_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhistorytable",
            name="action",
            field=models.CharField(
                choices=[
                    ("1", "Create"),
                    ("2", "Update"),
                    ("0", "Delete"),
                    ("3", "Restored"),
                    ("4", "Onboarded"),
                ],
                max_length=1,
            ),
        ),
    ]
