# Generated by Django 4.1.7 on 2023-03-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("superuseractions", "0016_userhistorytable_parent_entity_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userhistorytable",
            name="parent_entity_name",
        ),
    ]
