# Generated by Django 4.1.7 on 2023-03-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superuseractions", "0017_remove_userhistorytable_parent_entity_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistorytable",
            name="parent_entity_name",
            field=models.CharField(default="", max_length=32, null=True),
        ),
    ]
