# Generated by Django 4.1.6 on 2023-03-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofileadmin",
            name="prompt_credentials",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofileadmin",
            name="prompt_credentials",
            field=models.BooleanField(default=False),
        ),
    ]
